## YAML Template.
---

server:
  port: 8080
  
logging:
  level:
    org.springframework.cloud.gateway: WARN
    reactor.netty.http.client: WARN
    org.springframework.boot.autoconfigure: WARN 
    org.springframework.context: WARN
  
# Config for Feign Clients
services:
  customer:
    url: http://localhost:8081
  transaction:
    url: http://localhost:8082
    
spring:
  cloud:
    gateway:
      routes:
        # BFF Route
        - id: customer_bff
          uri: http://localhost:8080
          predicates:
            - Path=/customers-enriched/**
          filters:
            - RewritePath=/customers-enriched/(?<segment>.*), /bff/customers/$\{segment}
        
        # Routes to microservices
        - id: customer_service
          uri: http://localhost:8081 
          predicates:
            - Path=/customers/**
            
        - id: transaction_service
          uri: http://localhost:8082
          predicates:
            - Path=/transactions/**